### ISSUE TITLE
Attributions

### ISSUE THREAD

**Issue by vinber** [SteveCline/pdfmapmaker#2]
Hi,
please consider this https://www.openstreetmap.org/copyright/en
It's because I try your nice tool

**Comment by SteveCline** [comment]
OpenStreetMap is attributed on the bottom of the map page already along with Mapbox.

**Comment by vinber** [comment]
yes, but i think it's on the map normallly ?

**Comment by SteveCline** [comment]
Attribution can be on the map, but I chose to place it off the map and on the pdf output page to make it look more like the final output. This meets requirements for attributing both Mapbox and OpenStreetMap for their data.
